import { Inter } from "next/font/google";
import "./globals.css";
import MyContextProvider from "@/context/MyContextProvider";
import Sidebar from "@/components/Sidebar/Sidebar";
import Navbar from "@/components/Navbar/Navbar";
import { cookies } from 'next/headers'
import User from '@/models/UserSchema'
import { verify } from 'jsonwebtoken'


export const verifyAuthentication = async ()=>{
  const cookieStore = cookies();
  const token = cookieStore.get("token");

  if(!token) {
    return false;
  }

  const value = token.value;

    try{
        
      const decodeToken = verify(value,process.env.SECRET_KEY); 
      const userDb = await  User.findOne({_id : decodeToken.user.id});
  
      if(!userDb){
        return false;
      }

      return decodeToken.user;

    } catch(err){
        console.log(err)
    }
}

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

    const userDb = await verifyAuthentication();
  return (
    <html lang="en">
      <body className={`${inter.className} h-screen`}>
        <MyContextProvider>
          <Navbar user={userDb}/>
          <main className="w-full h-5/6 sm:min-h-[510px] sm:flex">
          <Sidebar/>
          {children}
          </main>
          </MyContextProvider>
        </body>
    </html>
  );
}
